// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team2231.robot.subsystems;

import org.usfirst.frc.team2231.robot.Robot;
import org.usfirst.frc.team2231.robot.RobotMap;
import org.usfirst.frc.team2231.robot.StaticFields;
import org.usfirst.frc.team2231.robot.commands.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Shooter extends Subsystem {
    private final CANTalon upperWheel = RobotMap.shooterUpperWheel;
    private final CANTalon lowerWheel = RobotMap.shooterLowerWheel;
    
	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}
	
	public void startShoot() {
		upperWheel.set(StaticFields.SHOOTER_SPEED);
		lowerWheel.set(StaticFields.SHOOTER_SPEED);
	}
	
	public void stopShoot() {
		upperWheel.set(0);
		lowerWheel.set(0);
	}
	
	public boolean isShooting(){
		return (upperWheel.get() == 0) && (lowerWheel.get() == 0);
	}
}
