// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2231.robot.commands;

import org.usfirst.frc.team2231.robot.Robot;
import org.usfirst.frc.team2231.robot.RobotMap;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class DriveByJoystick extends Command {

    public DriveByJoystick() {
        requires(Robot.driveTrain);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	RobotMap.driveTrainFirstLeft.set(0.05 * RobotMap.driveTrainFirstRight.get());
    	RobotMap.driveTrainFirstLeft.set(0.05 * RobotMap.driveTrainFirstRight.get());
    	Robot.driveTrain.arcadeDrive(Robot.oi.getDriveStick());
    	
//    	System.out.println("First Left Value : "+ RobotMap.driveTrainFirstLeft.get());
//    	System.out.println("Second Left Value : "+ RobotMap.driveTrainSecondLeft.get());
//    	System.out.println("First Right Value : "+ RobotMap.driveTrainFirstRight.get());
//    	System.out.println("Second Right Value : "+ RobotMap.driveTrainSecondRight.get());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
