// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2231.robot.commands;
import org.usfirst.frc.team2231.robot.Robot;
import org.usfirst.frc.team2231.robot.subsystems.GearBlocker;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class OpenGearBlocker extends Command {

    public OpenGearBlocker() {
        requires(Robot.gearBlocker); 
    }

    // Called once when this command runs
    protected void initialize() {
    }
    
    @Override
    protected void execute() {
    	Robot.gearBlocker.setGearBlocker(GearBlocker.BLOCKER_OPEN_POSIION, GearBlocker.MOTOR_OPEN_SPEED);
    }

	@Override
	protected boolean isFinished() {
		return Robot.gearBlocker.isOnTarget(GearBlocker.BLOCKER_OPEN_POSIION);
	}
	
	@Override
	protected void end() {
		Robot.gearBlocker.stopMotor();
	}

	@Override
	protected void interrupted() {
		end();
	}
}
