// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2231.robot.commands;

import org.usfirst.frc.team2231.robot.Robot;
import org.usfirst.frc.team2231.robot.RobotMap;

import OnyxTronix.Debug;
import OnyxTronix.SetPointCommand;
import edu.wpi.first.wpilibj.PIDSourceType;

/**
 *
 */
public class RotateByAngle extends SetPointCommand {
	
    public RotateByAngle(double setPoint, boolean isSubCommand) {
    	super(setPoint);
    	this.setPoint = Robot.driveTrain.getEfficientAngle(setPoint);
    	if(!isSubCommand) {
    		requires(Robot.driveTrain);
    	}
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	isFinished = false;
    	Robot.driveTrain.resetGyro();
    	Robot.driveTrain.setPIDSourceType(PIDSourceType.kDisplacement);
    	Robot.driveTrain.setRotateSlaveTalons();
    	Robot.driveTrain.initRotatePID(setPoint);
    	Debug.getInstance().log(this, "Angle set point: " + setPoint + "");
    	System.out.println("Angle set point: " + setPoint);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Debug.getInstance().log(this, "Left Output: " + RobotMap.driveTrainRotationLeftPIDController.get());
    	Debug.getInstance().log(this, "Right Output: " + RobotMap.driveTrainRotationRightPIDController.get());
    	
    	Debug.getInstance().log(this, "Left Error: " + RobotMap.driveTrainRotationLeftPIDController.getError());
    	Debug.getInstance().log(this, "Right Error: " + RobotMap.driveTrainRotationRightPIDController.getError());
    	isFinished = Robot.driveTrain.isRotateOnTarget();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.stopRotatePID();
    	Robot.driveTrain.resetSlaveTalons();
    	System.out.println("Finished");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
    
    @Override
    public void setSetPoint(double setPoint) {
		this.setPoint = Robot.driveTrain.getEfficientAngle(setPoint);
	}
}
