// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2231.robot.commands;
import org.usfirst.frc.team2231.robot.Robot;
import org.usfirst.frc.team2231.robot.RobotMap;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.InstantCommand;

/**
 *
 */
public class StartShoot extends Command {

    public StartShoot() {
        requires(Robot.shooter);
    }

    // Called once when this command runs
    protected void initialize() {
    	Robot.shooter.startShoot();
    }
    
    protected void execute() {
    }
    
    protected boolean isFinished() {
    	return false;
    }
    
    protected void end() {
    }
    
    protected void interrupted(){
    	Robot.shooter.stopShoot();
    }
}
