// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2231.robot.commands;

import org.usfirst.frc.team2231.robot.RobotMap;

import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.ConditionalCommand;

/**
 *
 */
public class ToggleGearHolder extends ConditionalCommand {


    public ToggleGearHolder() {
    	super(new OpenGearHolder(), new CloseGearHolder());
    }

    protected boolean condition(){
        return RobotMap.gearHolderLowerPiston.get() != Value.kReverse;
    }
}
